/** \file
 *  This C source file was generated by $ANTLR version 3.5.1
 *
 *     -  From the grammar source file : /home/ryan/Downloads/Kale.g
 *     -                            On : 2022-07-19 20:49:54
 *     -                 for the lexer : KaleLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "KaleLexer.h"
/* ----------------------------------------- */


/** String literals used by KaleLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x7C, 0x7C,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x26, 0x26,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x3D, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x21, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x66, 0x6E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x69, 0x66,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x65, 0x6C, 0x73, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x74, 0x72, 0x75, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x66, 0x61, 0x6C, 0x73, 0x65,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pKaleLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pKaleLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pKaleLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pKaleLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mLBRACE    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mRBRACE    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mLPAREN    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mRPAREN    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mSEMI    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mCOMMA    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mNL    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mSTATEMENT_DELIMITER    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mOP_ASSIGN    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mOP_ADD    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mOP_SUBTRACT    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mOP_MULTIPLY    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mOP_DIVIDE    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mOP_BOOL_INVERSE    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mOP_REL_OR    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mOP_REL_AND    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mOP_REL_EQ    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mOP_REL_NEQ    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mKEYWORD_METHOD    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mKEYWORD_IF    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mKEYWORD_ELSE    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mNUMBER    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mEXPONENT    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mSTRING    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mCHAR    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mBOOLEAN    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mIDENTIFIER    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mWS    (pKaleLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (pKaleLexer ctx);
static void	KaleLexerFree(pKaleLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
KaleLexerFree  (pKaleLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
KaleLexerReset (pKaleLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/home/ryan/Downloads/Kale.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called KaleLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pKaleLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pKaleLexer KaleLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return KaleLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called KaleLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pKaleLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pKaleLexer KaleLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pKaleLexer ctx; // Context structure we will build and return

    ctx = (pKaleLexer) ANTLR3_CALLOC(1, sizeof(KaleLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in KaleLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our KaleLexer interface
     */
    ctx->mLBRACE	= mLBRACE;
    ctx->mRBRACE	= mRBRACE;
    ctx->mLPAREN	= mLPAREN;
    ctx->mRPAREN	= mRPAREN;
    ctx->mSEMI	= mSEMI;
    ctx->mCOMMA	= mCOMMA;
    ctx->mNL	= mNL;
    ctx->mSTATEMENT_DELIMITER	= mSTATEMENT_DELIMITER;
    ctx->mOP_ASSIGN	= mOP_ASSIGN;
    ctx->mOP_ADD	= mOP_ADD;
    ctx->mOP_SUBTRACT	= mOP_SUBTRACT;
    ctx->mOP_MULTIPLY	= mOP_MULTIPLY;
    ctx->mOP_DIVIDE	= mOP_DIVIDE;
    ctx->mOP_BOOL_INVERSE	= mOP_BOOL_INVERSE;
    ctx->mOP_REL_OR	= mOP_REL_OR;
    ctx->mOP_REL_AND	= mOP_REL_AND;
    ctx->mOP_REL_EQ	= mOP_REL_EQ;
    ctx->mOP_REL_NEQ	= mOP_REL_NEQ;
    ctx->mKEYWORD_METHOD	= mKEYWORD_METHOD;
    ctx->mKEYWORD_IF	= mKEYWORD_IF;
    ctx->mKEYWORD_ELSE	= mKEYWORD_ELSE;
    ctx->mNUMBER	= mNUMBER;
    ctx->mEXPONENT	= mEXPONENT;
    ctx->mSTRING	= mSTRING;
    ctx->mCHAR	= mCHAR;
    ctx->mBOOLEAN	= mBOOLEAN;
    ctx->mIDENTIFIER	= mIDENTIFIER;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= KaleLexerFree;
    ctx->reset          = KaleLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}

/* =========================================================================
 * DFA tables for the lexer
 */
/** Static dfa state tables for Cyclic dfa:
 *    108:1: NUMBER : ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ ( EXPONENT )? );
 */
static const ANTLR3_INT32 dfa11_eot[5] =
    {
	-1, 4, -1, -1, -1
    };
static const ANTLR3_INT32 dfa11_eof[5] =
    {
	-1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa11_min[5] =
    {
	46, 46, -1, -1, -1
    };
static const ANTLR3_INT32 dfa11_max[5] =
    {
	57, 57, -1, -1, -1
    };
static const ANTLR3_INT32 dfa11_accept[5] =
    {
	-1, -1, 2, 1, 3
    };
static const ANTLR3_INT32 dfa11_special[5] =
    {
	-1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define _empty	    NULL

static const ANTLR3_INT32 dfa11_T0[] =
    {
	2, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
    };
static const ANTLR3_INT32 dfa11_T1[] =
    {
	3, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
    };

/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa11_transitions[] =
{
    dfa11_T0, dfa11_T1, _empty, _empty, _empty
};


/* Declare tracking structure for Cyclic DFA 11
 */
static
ANTLR3_CYCLIC_DFA cdfa11
    =	{
	    11,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"108:1: NUMBER : ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ ( EXPONENT )? );",
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/

	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa11_eot,	    /* EOT table			    */
	    dfa11_eof,	    /* EOF table			    */
	    dfa11_min,	    /* Minimum tokens for each state    */
	    dfa11_max,	    /* Maximum tokens for each state    */
	    dfa11_accept,	/* Accept table			    */
	    dfa11_special,	/* Special transition states	    */
	    dfa11_transitions	/* Table of transition tables	    */

	};
/* End of Cyclic DFA 11
 * ---------------------
 *//** Static dfa state tables for Cyclic dfa:
 *    1:1: Tokens : ( LBRACE | RBRACE | LPAREN | RPAREN | SEMI | COMMA | NL | STATEMENT_DELIMITER | OP_ASSIGN | OP_ADD | OP_SUBTRACT | OP_MULTIPLY | OP_DIVIDE | OP_BOOL_INVERSE | OP_REL_OR | OP_REL_AND | OP_REL_EQ | OP_REL_NEQ | KEYWORD_METHOD | KEYWORD_IF | KEYWORD_ELSE | NUMBER | EXPONENT | STRING | CHAR | BOOLEAN | IDENTIFIER | WS );
 */
static const ANTLR3_INT32 dfa18_eot[54] =
    {
	-1, -1, -1, -1, -1, 27, -1, 29, 29, 33, -1, -1, -1, -1, 35, -1, -1, 25, 
	25, 25, -1, 25, -1, -1, 25, -1, -1, -1, -1, -1, 28, 29, -1, -1, -1, -1, 
	43, 25, 45, 25, -1, 40, 25, -1, 25, -1, 25, 25, 25, 52, 53, 53, -1, -1
    };
static const ANTLR3_INT32 dfa18_eof[54] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa18_min[54] =
    {
	10, -1, -1, -1, -1, 10, -1, 10, 10, 61, -1, -1, -1, -1, 61, -1, -1, 97, 
	102, 43, -1, 43, -1, -1, 114, -1, -1, -1, -1, -1, 10, 10, -1, -1, -1, -1, 
	48, 108, 48, 115, -1, 48, 117, -1, 115, -1, 101, 101, 101, 48, 48, 48, 
	-1, -1
    };
static const ANTLR3_INT32 dfa18_max[54] =
    {
	125, -1, -1, -1, -1, 59, -1, 59, 59, 61, -1, -1, -1, -1, 61, -1, -1, 110, 
	102, 108, -1, 57, -1, -1, 114, -1, -1, -1, -1, -1, 32, 59, -1, -1, -1, 
	-1, 122, 108, 122, 115, -1, 122, 117, -1, 115, -1, 101, 101, 101, 122, 
	122, 122, -1, -1
    };
static const ANTLR3_INT32 dfa18_accept[54] =
    {
	-1, 1, 2, 3, 4, -1, 6, -1, -1, -1, 10, 11, 12, 13, -1, 15, 16, -1, -1, 
	-1, 22, -1, 24, 25, -1, 27, 28, 5, 8, 7, -1, -1, 17, 9, 18, 14, -1, -1, 
	-1, -1, 23, -1, -1, 19, -1, 20, -1, -1, -1, -1, -1, -1, 21, 26
    };
static const ANTLR3_INT32 dfa18_special[54] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa18_T_empty	    NULL

static const ANTLR3_INT32 dfa18_T0[] =
    {
	47
    };
static const ANTLR3_INT32 dfa18_T1[] =
    {
	7, -1, -1, 8, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, 26, 14, 22, -1, -1, -1, 16, 23, 3, 4, 12, 10, 6, 11, 20, 13, 
	20, 20, 20, 20, 20, 20, 20, 20, 20, 20, -1, 5, -1, 9, -1, -1, -1, 25, 25, 
	25, 25, 21, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 
	25, 25, 25, 25, 25, 25, -1, -1, -1, -1, 25, -1, 25, 25, 25, 25, 19, 17, 
	25, 25, 18, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 24, 25, 25, 25, 25, 
	25, 25, 1, 15, 2
    };
static const ANTLR3_INT32 dfa18_T2[] =
    {
	50
    };
static const ANTLR3_INT32 dfa18_T3[] =
    {
	44
    };
static const ANTLR3_INT32 dfa18_T4[] =
    {
	31, -1, -1, 28, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 28
    };
static const ANTLR3_INT32 dfa18_T5[] =
    {
	48
    };
static const ANTLR3_INT32 dfa18_T6[] =
    {
	51
    };
static const ANTLR3_INT32 dfa18_T7[] =
    {
	40, -1, 40, -1, -1, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41
    };
static const ANTLR3_INT32 dfa18_T8[] =
    {
	42
    };
static const ANTLR3_INT32 dfa18_T9[] =
    {
	30, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, 26
    };
static const ANTLR3_INT32 dfa18_T10[] =
    {
	41, 41, 41, 41, 41, 41, 41, 41, 41, 41, -1, -1, -1, -1, -1, -1, -1, 25, 
	25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 
	25, 25, 25, 25, 25, 25, 25, -1, -1, -1, -1, 25, -1, 25, 25, 25, 25, 25, 
	25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 
	25, 25, 25
    };
static const ANTLR3_INT32 dfa18_T11[] =
    {
	25, 25, 25, 25, 25, 25, 25, 25, 25, 25, -1, -1, -1, -1, -1, -1, -1, 25, 
	25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 
	25, 25, 25, 25, 25, 25, 25, -1, -1, -1, -1, 25, -1, 25, 25, 25, 25, 25, 
	25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 
	25, 25, 25
    };
static const ANTLR3_INT32 dfa18_T12[] =
    {
	46
    };
static const ANTLR3_INT32 dfa18_T13[] =
    {
	49
    };
static const ANTLR3_INT32 dfa18_T14[] =
    {
	32
    };
static const ANTLR3_INT32 dfa18_T15[] =
    {
	40, -1, 40, -1, -1, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 39
    };
static const ANTLR3_INT32 dfa18_T16[] =
    {
	37, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 36
    };
static const ANTLR3_INT32 dfa18_T17[] =
    {
	38
    };
static const ANTLR3_INT32 dfa18_T18[] =
    {
	28, -1, -1, 28, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 28
    };
static const ANTLR3_INT32 dfa18_T19[] =
    {
	34
    };
static const ANTLR3_INT32 dfa18_T20[] =
    {
	30, -1, -1, 28, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, 26, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 28
    };

/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa18_transitions[] =
{
    dfa18_T1, _empty, _empty, _empty, _empty, dfa18_T18, _empty, dfa18_T20, 
    dfa18_T4, dfa18_T14, _empty, _empty, _empty, _empty, dfa18_T19, _empty, 
    _empty, dfa18_T16, dfa18_T17, dfa18_T15, _empty, dfa18_T7, _empty, _empty, 
    dfa18_T8, _empty, _empty, _empty, _empty, _empty, dfa18_T9, dfa18_T18, 
    _empty, _empty, _empty, _empty, dfa18_T11, dfa18_T3, dfa18_T11, dfa18_T12, 
    _empty, dfa18_T10, dfa18_T0, _empty, dfa18_T5, _empty, dfa18_T13, dfa18_T2, 
    dfa18_T6, dfa18_T11, dfa18_T11, dfa18_T11, _empty, _empty
};


/* Declare tracking structure for Cyclic DFA 18
 */
static
ANTLR3_CYCLIC_DFA cdfa18
    =	{
	    18,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"1:1: Tokens : ( LBRACE | RBRACE | LPAREN | RPAREN | SEMI | COMMA | NL | STATEMENT_DELIMITER | OP_ASSIGN | OP_ADD | OP_SUBTRACT | OP_MULTIPLY | OP_DIVIDE | OP_BOOL_INVERSE | OP_REL_OR | OP_REL_AND | OP_REL_EQ | OP_REL_NEQ | KEYWORD_METHOD | KEYWORD_IF | KEYWORD_ELSE | NUMBER | EXPONENT | STRING | CHAR | BOOLEAN | IDENTIFIER | WS );",
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/

	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa18_eot,	    /* EOT table			    */
	    dfa18_eof,	    /* EOF table			    */
	    dfa18_min,	    /* Minimum tokens for each state    */
	    dfa18_max,	    /* Maximum tokens for each state    */
	    dfa18_accept,	/* Accept table			    */
	    dfa18_special,	/* Special transition states	    */
	    dfa18_transitions	/* Table of transition tables	    */

	};
/* End of Cyclic DFA 18
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the lexer
 */

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 79:7: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LBRACE
 *
 * Looks to match the characters the constitute the token LBRACE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLBRACE(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LBRACE;


    // /home/ryan/Downloads/Kale.g:79:7: ( '{' )
    // /home/ryan/Downloads/Kale.g:79:9: '{'
    {
        MATCHC('{');
        if  (HASEXCEPTION())
        {
            goto ruleLBRACEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLBRACEEx; /* Prevent compiler warnings */
    ruleLBRACEEx: ;

}
// $ANTLR end LBRACE

//   Comes from: 80:7: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RBRACE
 *
 * Looks to match the characters the constitute the token RBRACE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRBRACE(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = RBRACE;


    // /home/ryan/Downloads/Kale.g:80:7: ( '}' )
    // /home/ryan/Downloads/Kale.g:80:9: '}'
    {
        MATCHC('}');
        if  (HASEXCEPTION())
        {
            goto ruleRBRACEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleRBRACEEx; /* Prevent compiler warnings */
    ruleRBRACEEx: ;

}
// $ANTLR end RBRACE

//   Comes from: 81:7: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LPAREN
 *
 * Looks to match the characters the constitute the token LPAREN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLPAREN(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LPAREN;


    // /home/ryan/Downloads/Kale.g:81:7: ( '(' )
    // /home/ryan/Downloads/Kale.g:81:9: '('
    {
        MATCHC('(');
        if  (HASEXCEPTION())
        {
            goto ruleLPARENEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLPARENEx; /* Prevent compiler warnings */
    ruleLPARENEx: ;

}
// $ANTLR end LPAREN

//   Comes from: 82:7: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RPAREN
 *
 * Looks to match the characters the constitute the token RPAREN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRPAREN(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = RPAREN;


    // /home/ryan/Downloads/Kale.g:82:7: ( ')' )
    // /home/ryan/Downloads/Kale.g:82:9: ')'
    {
        MATCHC(')');
        if  (HASEXCEPTION())
        {
            goto ruleRPARENEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleRPARENEx; /* Prevent compiler warnings */
    ruleRPARENEx: ;

}
// $ANTLR end RPAREN

//   Comes from: 83:5: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start SEMI
 *
 * Looks to match the characters the constitute the token SEMI
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSEMI(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = SEMI;


    // /home/ryan/Downloads/Kale.g:83:5: ( ';' )
    // /home/ryan/Downloads/Kale.g:83:9: ';'
    {
        MATCHC(';');
        if  (HASEXCEPTION())
        {
            goto ruleSEMIEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSEMIEx; /* Prevent compiler warnings */
    ruleSEMIEx: ;

}
// $ANTLR end SEMI

//   Comes from: 84:6: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COMMA
 *
 * Looks to match the characters the constitute the token COMMA
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOMMA(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = COMMA;


    // /home/ryan/Downloads/Kale.g:84:6: ( ',' )
    // /home/ryan/Downloads/Kale.g:84:9: ','
    {
        MATCHC(',');
        if  (HASEXCEPTION())
        {
            goto ruleCOMMAEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCOMMAEx; /* Prevent compiler warnings */
    ruleCOMMAEx: ;

}
// $ANTLR end COMMA

//   Comes from: 85:3: ( '\\n' | '\\r' ( '\\n' )? )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NL
 *
 * Looks to match the characters the constitute the token NL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNL(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NL;


    {
        //  /home/ryan/Downloads/Kale.g:85:3: ( '\\n' | '\\r' ( '\\n' )? )

        ANTLR3_UINT32 alt2;

        alt2=2;

        switch ( LA(1) )
        {
        case '\n':
        	{
        		alt2=1;
        	}
            break;
        case '\r':
        	{
        		alt2=2;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 2;
            EXCEPTION->state        = 0;


            goto ruleNLEx;

        }

        switch (alt2)
        {
    	case 1:
    	    // /home/ryan/Downloads/Kale.g:85:9: '\\n'
    	    {
    	        MATCHC('\n');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleNLEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // /home/ryan/Downloads/Kale.g:85:16: '\\r' ( '\\n' )?
    	    {
    	        MATCHC('\r');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleNLEx;
    	        }


    	        // /home/ryan/Downloads/Kale.g:85:21: ( '\\n' )?
    	        {
    	            int alt1=2;
    	            switch ( LA(1) )
    	            {
    	                case '\n':
    	                	{
    	                		alt1=1;
    	                	}
    	                    break;
    	            }

    	            switch (alt1)
    	            {
    	        	case 1:
    	        	    // /home/ryan/Downloads/Kale.g:85:21: '\\n'
    	        	    {
    	        	        MATCHC('\n');
    	        	        if  (HASEXCEPTION())
    	        	        {
    	        	            goto ruleNLEx;
    	        	        }


    	        	    }
    	        	    break;

    	            }
    	        }

    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNLEx; /* Prevent compiler warnings */
    ruleNLEx: ;

}
// $ANTLR end NL

//   Comes from: 88:3: ( ( SEMI | NL )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STATEMENT_DELIMITER
 *
 * Looks to match the characters the constitute the token STATEMENT_DELIMITER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTATEMENT_DELIMITER(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = STATEMENT_DELIMITER;


    // /home/ryan/Downloads/Kale.g:88:3: ( ( SEMI | NL )+ )
    // /home/ryan/Downloads/Kale.g:88:5: ( SEMI | NL )+
    {
        // /home/ryan/Downloads/Kale.g:88:5: ( SEMI | NL )+
        {
            int cnt3=0;

            for (;;)
            {
                int alt3=3;
        	switch ( LA(1) )
        	{
        	case ';':
        		{
        			alt3=1;
        		}
        	    break;
        	case '\n':
        	case '\r':
        		{
        			alt3=2;
        		}
        	    break;

        	}

        	switch (alt3)
        	{
        	    case 1:
        	        // /home/ryan/Downloads/Kale.g:88:6: SEMI
        	        {
        	            /* 88:6: SEMI */
        	            mSEMI(ctx );
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleSTATEMENT_DELIMITEREx;
        	            }



        	        }
        	        break;
        	    case 2:
        	        // /home/ryan/Downloads/Kale.g:88:13: NL
        	        {
        	            /* 88:13: NL */
        	            mNL(ctx );
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleSTATEMENT_DELIMITEREx;
        	            }



        	        }
        	        break;

        	    default:

        		if ( cnt3 >= 1 )
        		{
        		    goto loop3;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleSTATEMENT_DELIMITEREx;
        	}
        	cnt3++;
            }
            loop3: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSTATEMENT_DELIMITEREx; /* Prevent compiler warnings */
    ruleSTATEMENT_DELIMITEREx: ;

}
// $ANTLR end STATEMENT_DELIMITER

//   Comes from: 91:10: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OP_ASSIGN
 *
 * Looks to match the characters the constitute the token OP_ASSIGN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOP_ASSIGN(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OP_ASSIGN;


    // /home/ryan/Downloads/Kale.g:91:10: ( '=' )
    // /home/ryan/Downloads/Kale.g:91:14: '='
    {
        MATCHC('=');
        if  (HASEXCEPTION())
        {
            goto ruleOP_ASSIGNEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOP_ASSIGNEx; /* Prevent compiler warnings */
    ruleOP_ASSIGNEx: ;

}
// $ANTLR end OP_ASSIGN

//   Comes from: 92:7: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OP_ADD
 *
 * Looks to match the characters the constitute the token OP_ADD
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOP_ADD(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OP_ADD;


    // /home/ryan/Downloads/Kale.g:92:7: ( '+' )
    // /home/ryan/Downloads/Kale.g:92:14: '+'
    {
        MATCHC('+');
        if  (HASEXCEPTION())
        {
            goto ruleOP_ADDEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOP_ADDEx; /* Prevent compiler warnings */
    ruleOP_ADDEx: ;

}
// $ANTLR end OP_ADD

//   Comes from: 93:12: ( '-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OP_SUBTRACT
 *
 * Looks to match the characters the constitute the token OP_SUBTRACT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOP_SUBTRACT(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OP_SUBTRACT;


    // /home/ryan/Downloads/Kale.g:93:12: ( '-' )
    // /home/ryan/Downloads/Kale.g:93:14: '-'
    {
        MATCHC('-');
        if  (HASEXCEPTION())
        {
            goto ruleOP_SUBTRACTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOP_SUBTRACTEx; /* Prevent compiler warnings */
    ruleOP_SUBTRACTEx: ;

}
// $ANTLR end OP_SUBTRACT

//   Comes from: 94:12: ( '*' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OP_MULTIPLY
 *
 * Looks to match the characters the constitute the token OP_MULTIPLY
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOP_MULTIPLY(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OP_MULTIPLY;


    // /home/ryan/Downloads/Kale.g:94:12: ( '*' )
    // /home/ryan/Downloads/Kale.g:94:14: '*'
    {
        MATCHC('*');
        if  (HASEXCEPTION())
        {
            goto ruleOP_MULTIPLYEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOP_MULTIPLYEx; /* Prevent compiler warnings */
    ruleOP_MULTIPLYEx: ;

}
// $ANTLR end OP_MULTIPLY

//   Comes from: 95:10: ( '/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OP_DIVIDE
 *
 * Looks to match the characters the constitute the token OP_DIVIDE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOP_DIVIDE(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OP_DIVIDE;


    // /home/ryan/Downloads/Kale.g:95:10: ( '/' )
    // /home/ryan/Downloads/Kale.g:95:14: '/'
    {
        MATCHC('/');
        if  (HASEXCEPTION())
        {
            goto ruleOP_DIVIDEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOP_DIVIDEEx; /* Prevent compiler warnings */
    ruleOP_DIVIDEEx: ;

}
// $ANTLR end OP_DIVIDE

//   Comes from: 97:16: ( '!' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OP_BOOL_INVERSE
 *
 * Looks to match the characters the constitute the token OP_BOOL_INVERSE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOP_BOOL_INVERSE(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OP_BOOL_INVERSE;


    // /home/ryan/Downloads/Kale.g:97:16: ( '!' )
    // /home/ryan/Downloads/Kale.g:97:18: '!'
    {
        MATCHC('!');
        if  (HASEXCEPTION())
        {
            goto ruleOP_BOOL_INVERSEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOP_BOOL_INVERSEEx; /* Prevent compiler warnings */
    ruleOP_BOOL_INVERSEEx: ;

}
// $ANTLR end OP_BOOL_INVERSE

//   Comes from: 99:10: ( '||' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OP_REL_OR
 *
 * Looks to match the characters the constitute the token OP_REL_OR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOP_REL_OR(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OP_REL_OR;


    // /home/ryan/Downloads/Kale.g:99:10: ( '||' )
    // /home/ryan/Downloads/Kale.g:99:14: '||'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleOP_REL_OREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOP_REL_OREx; /* Prevent compiler warnings */
    ruleOP_REL_OREx: ;

}
// $ANTLR end OP_REL_OR

//   Comes from: 100:11: ( '&&' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OP_REL_AND
 *
 * Looks to match the characters the constitute the token OP_REL_AND
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOP_REL_AND(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OP_REL_AND;


    // /home/ryan/Downloads/Kale.g:100:11: ( '&&' )
    // /home/ryan/Downloads/Kale.g:100:14: '&&'
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleOP_REL_ANDEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOP_REL_ANDEx; /* Prevent compiler warnings */
    ruleOP_REL_ANDEx: ;

}
// $ANTLR end OP_REL_AND

//   Comes from: 101:10: ( '==' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OP_REL_EQ
 *
 * Looks to match the characters the constitute the token OP_REL_EQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOP_REL_EQ(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OP_REL_EQ;


    // /home/ryan/Downloads/Kale.g:101:10: ( '==' )
    // /home/ryan/Downloads/Kale.g:101:14: '=='
    {
        MATCHS(lit_3);
        if  (HASEXCEPTION())
        {
            goto ruleOP_REL_EQEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOP_REL_EQEx; /* Prevent compiler warnings */
    ruleOP_REL_EQEx: ;

}
// $ANTLR end OP_REL_EQ

//   Comes from: 102:11: ( '!=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OP_REL_NEQ
 *
 * Looks to match the characters the constitute the token OP_REL_NEQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOP_REL_NEQ(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OP_REL_NEQ;


    // /home/ryan/Downloads/Kale.g:102:11: ( '!=' )
    // /home/ryan/Downloads/Kale.g:102:14: '!='
    {
        MATCHS(lit_4);
        if  (HASEXCEPTION())
        {
            goto ruleOP_REL_NEQEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOP_REL_NEQEx; /* Prevent compiler warnings */
    ruleOP_REL_NEQEx: ;

}
// $ANTLR end OP_REL_NEQ

//   Comes from: 104:15: ( 'fn' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start KEYWORD_METHOD
 *
 * Looks to match the characters the constitute the token KEYWORD_METHOD
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mKEYWORD_METHOD(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = KEYWORD_METHOD;


    // /home/ryan/Downloads/Kale.g:104:15: ( 'fn' )
    // /home/ryan/Downloads/Kale.g:104:17: 'fn'
    {
        MATCHS(lit_5);
        if  (HASEXCEPTION())
        {
            goto ruleKEYWORD_METHODEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleKEYWORD_METHODEx; /* Prevent compiler warnings */
    ruleKEYWORD_METHODEx: ;

}
// $ANTLR end KEYWORD_METHOD

//   Comes from: 105:11: ( 'if' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start KEYWORD_IF
 *
 * Looks to match the characters the constitute the token KEYWORD_IF
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mKEYWORD_IF(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = KEYWORD_IF;


    // /home/ryan/Downloads/Kale.g:105:11: ( 'if' )
    // /home/ryan/Downloads/Kale.g:105:25: 'if'
    {
        MATCHS(lit_6);
        if  (HASEXCEPTION())
        {
            goto ruleKEYWORD_IFEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleKEYWORD_IFEx; /* Prevent compiler warnings */
    ruleKEYWORD_IFEx: ;

}
// $ANTLR end KEYWORD_IF

//   Comes from: 106:13: ( 'else' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start KEYWORD_ELSE
 *
 * Looks to match the characters the constitute the token KEYWORD_ELSE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mKEYWORD_ELSE(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = KEYWORD_ELSE;


    // /home/ryan/Downloads/Kale.g:106:13: ( 'else' )
    // /home/ryan/Downloads/Kale.g:106:21: 'else'
    {
        MATCHS(lit_7);
        if  (HASEXCEPTION())
        {
            goto ruleKEYWORD_ELSEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleKEYWORD_ELSEEx; /* Prevent compiler warnings */
    ruleKEYWORD_ELSEEx: ;

}
// $ANTLR end KEYWORD_ELSE

//   Comes from: 109:3: ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ ( EXPONENT )? )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NUMBER
 *
 * Looks to match the characters the constitute the token NUMBER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNUMBER(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NUMBER;


    {
        //  /home/ryan/Downloads/Kale.g:109:3: ( ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )? | '.' ( '0' .. '9' )+ ( EXPONENT )? | ( '0' .. '9' )+ ( EXPONENT )? )

        ANTLR3_UINT32 alt11;

        alt11=3;

        alt11 = cdfa11.predict(ctx, RECOGNIZER, ISTREAM, &cdfa11);
        if  (HASEXCEPTION())
        {
            goto ruleNUMBEREx;
        }

        switch (alt11)
        {
    	case 1:
    	    // /home/ryan/Downloads/Kale.g:109:5: ( '0' .. '9' )+ '.' ( '0' .. '9' )* ( EXPONENT )?
    	    {
    	        // /home/ryan/Downloads/Kale.g:109:5: ( '0' .. '9' )+
    	        {
    	            int cnt4=0;

    	            for (;;)
    	            {
    	                int alt4=2;
    	        	switch ( LA(1) )
    	        	{
    	        	case '0':
    	        	case '1':
    	        	case '2':
    	        	case '3':
    	        	case '4':
    	        	case '5':
    	        	case '6':
    	        	case '7':
    	        	case '8':
    	        	case '9':
    	        		{
    	        			alt4=1;
    	        		}
    	        	    break;

    	        	}

    	        	switch (alt4)
    	        	{
    	        	    case 1:
    	        	        // /home/ryan/Downloads/Kale.g:
    	        	        {
    	        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
    	        	            {
    	        	                CONSUME();
    	        	            }
    	        	            else
    	        	            {
    	        	                CONSTRUCTEX();
    	        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	                LRECOVER();
    	        	                goto ruleNUMBEREx;
    	        	            }


    	        	        }
    	        	        break;

    	        	    default:

    	        		if ( cnt4 >= 1 )
    	        		{
    	        		    goto loop4;
    	        		}
    	        		/* mismatchedSetEx()
    	        		 */
    	        		CONSTRUCTEX();
    	        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
    	        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


    	        		goto ruleNUMBEREx;
    	        	}
    	        	cnt4++;
    	            }
    	            loop4: ;	/* Jump to here if this rule does not match */
    	        }

    	        MATCHC('.');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleNUMBEREx;
    	        }


    	        // /home/ryan/Downloads/Kale.g:109:21: ( '0' .. '9' )*

    	        for (;;)
    	        {
    	            int alt5=2;
    	            switch ( LA(1) )
    	            {
    	            case '0':
    	            case '1':
    	            case '2':
    	            case '3':
    	            case '4':
    	            case '5':
    	            case '6':
    	            case '7':
    	            case '8':
    	            case '9':
    	            	{
    	            		alt5=1;
    	            	}
    	                break;

    	            }

    	            switch (alt5)
    	            {
    	        	case 1:
    	        	    // /home/ryan/Downloads/Kale.g:
    	        	    {
    	        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
    	        	        {
    	        	            CONSUME();
    	        	        }
    	        	        else
    	        	        {
    	        	            CONSTRUCTEX();
    	        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	            LRECOVER();
    	        	            goto ruleNUMBEREx;
    	        	        }


    	        	    }
    	        	    break;

    	        	default:
    	        	    goto loop5;	/* break out of the loop */
    	        	    break;
    	            }
    	        }
    	        loop5: ; /* Jump out to here if this rule does not match */


    	        // /home/ryan/Downloads/Kale.g:109:33: ( EXPONENT )?
    	        {
    	            int alt6=2;
    	            switch ( LA(1) )
    	            {
    	                case 'E':
    	                case 'e':
    	                	{
    	                		alt6=1;
    	                	}
    	                    break;
    	            }

    	            switch (alt6)
    	            {
    	        	case 1:
    	        	    // /home/ryan/Downloads/Kale.g:109:33: EXPONENT
    	        	    {
    	        	        /* 109:33: EXPONENT */
    	        	        mEXPONENT(ctx );
    	        	        if  (HASEXCEPTION())
    	        	        {
    	        	            goto ruleNUMBEREx;
    	        	        }



    	        	    }
    	        	    break;

    	            }
    	        }

    	    }
    	    break;
    	case 2:
    	    // /home/ryan/Downloads/Kale.g:110:5: '.' ( '0' .. '9' )+ ( EXPONENT )?
    	    {
    	        MATCHC('.');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleNUMBEREx;
    	        }


    	        // /home/ryan/Downloads/Kale.g:110:9: ( '0' .. '9' )+
    	        {
    	            int cnt7=0;

    	            for (;;)
    	            {
    	                int alt7=2;
    	        	switch ( LA(1) )
    	        	{
    	        	case '0':
    	        	case '1':
    	        	case '2':
    	        	case '3':
    	        	case '4':
    	        	case '5':
    	        	case '6':
    	        	case '7':
    	        	case '8':
    	        	case '9':
    	        		{
    	        			alt7=1;
    	        		}
    	        	    break;

    	        	}

    	        	switch (alt7)
    	        	{
    	        	    case 1:
    	        	        // /home/ryan/Downloads/Kale.g:
    	        	        {
    	        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
    	        	            {
    	        	                CONSUME();
    	        	            }
    	        	            else
    	        	            {
    	        	                CONSTRUCTEX();
    	        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	                LRECOVER();
    	        	                goto ruleNUMBEREx;
    	        	            }


    	        	        }
    	        	        break;

    	        	    default:

    	        		if ( cnt7 >= 1 )
    	        		{
    	        		    goto loop7;
    	        		}
    	        		/* mismatchedSetEx()
    	        		 */
    	        		CONSTRUCTEX();
    	        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
    	        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


    	        		goto ruleNUMBEREx;
    	        	}
    	        	cnt7++;
    	            }
    	            loop7: ;	/* Jump to here if this rule does not match */
    	        }

    	        // /home/ryan/Downloads/Kale.g:110:21: ( EXPONENT )?
    	        {
    	            int alt8=2;
    	            switch ( LA(1) )
    	            {
    	                case 'E':
    	                case 'e':
    	                	{
    	                		alt8=1;
    	                	}
    	                    break;
    	            }

    	            switch (alt8)
    	            {
    	        	case 1:
    	        	    // /home/ryan/Downloads/Kale.g:110:21: EXPONENT
    	        	    {
    	        	        /* 110:21: EXPONENT */
    	        	        mEXPONENT(ctx );
    	        	        if  (HASEXCEPTION())
    	        	        {
    	        	            goto ruleNUMBEREx;
    	        	        }



    	        	    }
    	        	    break;

    	            }
    	        }

    	    }
    	    break;
    	case 3:
    	    // /home/ryan/Downloads/Kale.g:111:5: ( '0' .. '9' )+ ( EXPONENT )?
    	    {
    	        // /home/ryan/Downloads/Kale.g:111:5: ( '0' .. '9' )+
    	        {
    	            int cnt9=0;

    	            for (;;)
    	            {
    	                int alt9=2;
    	        	switch ( LA(1) )
    	        	{
    	        	case '0':
    	        	case '1':
    	        	case '2':
    	        	case '3':
    	        	case '4':
    	        	case '5':
    	        	case '6':
    	        	case '7':
    	        	case '8':
    	        	case '9':
    	        		{
    	        			alt9=1;
    	        		}
    	        	    break;

    	        	}

    	        	switch (alt9)
    	        	{
    	        	    case 1:
    	        	        // /home/ryan/Downloads/Kale.g:
    	        	        {
    	        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
    	        	            {
    	        	                CONSUME();
    	        	            }
    	        	            else
    	        	            {
    	        	                CONSTRUCTEX();
    	        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	                LRECOVER();
    	        	                goto ruleNUMBEREx;
    	        	            }


    	        	        }
    	        	        break;

    	        	    default:

    	        		if ( cnt9 >= 1 )
    	        		{
    	        		    goto loop9;
    	        		}
    	        		/* mismatchedSetEx()
    	        		 */
    	        		CONSTRUCTEX();
    	        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
    	        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


    	        		goto ruleNUMBEREx;
    	        	}
    	        	cnt9++;
    	            }
    	            loop9: ;	/* Jump to here if this rule does not match */
    	        }

    	        // /home/ryan/Downloads/Kale.g:111:17: ( EXPONENT )?
    	        {
    	            int alt10=2;
    	            switch ( LA(1) )
    	            {
    	                case 'E':
    	                case 'e':
    	                	{
    	                		alt10=1;
    	                	}
    	                    break;
    	            }

    	            switch (alt10)
    	            {
    	        	case 1:
    	        	    // /home/ryan/Downloads/Kale.g:111:17: EXPONENT
    	        	    {
    	        	        /* 111:17: EXPONENT */
    	        	        mEXPONENT(ctx );
    	        	        if  (HASEXCEPTION())
    	        	        {
    	        	            goto ruleNUMBEREx;
    	        	        }



    	        	    }
    	        	    break;

    	            }
    	        }

    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNUMBEREx; /* Prevent compiler warnings */
    ruleNUMBEREx: ;

}
// $ANTLR end NUMBER

//   Comes from: 113:9: ( ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EXPONENT
 *
 * Looks to match the characters the constitute the token EXPONENT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEXPONENT(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = EXPONENT;


    // /home/ryan/Downloads/Kale.g:113:9: ( ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+ )
    // /home/ryan/Downloads/Kale.g:113:11: ( 'e' | 'E' ) ( '+' | '-' )? ( '0' .. '9' )+
    {
        if ( LA(1) == 'E' || LA(1) == 'e' )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleEXPONENTEx;
        }


        // /home/ryan/Downloads/Kale.g:113:21: ( '+' | '-' )?
        {
            int alt12=2;
            switch ( LA(1) )
            {
                case '+':
                case '-':
                	{
                		alt12=1;
                	}
                    break;
            }

            switch (alt12)
            {
        	case 1:
        	    // /home/ryan/Downloads/Kale.g:
        	    {
        	        if ( LA(1) == '+' || LA(1) == '-' )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleEXPONENTEx;
        	        }


        	    }
        	    break;

            }
        }

        // /home/ryan/Downloads/Kale.g:113:32: ( '0' .. '9' )+
        {
            int cnt13=0;

            for (;;)
            {
                int alt13=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt13=1;
        		}
        	    break;

        	}

        	switch (alt13)
        	{
        	    case 1:
        	        // /home/ryan/Downloads/Kale.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleEXPONENTEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt13 >= 1 )
        		{
        		    goto loop13;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleEXPONENTEx;
        	}
        	cnt13++;
            }
            loop13: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleEXPONENTEx; /* Prevent compiler warnings */
    ruleEXPONENTEx: ;

}
// $ANTLR end EXPONENT

//   Comes from: 115:3: ( '\"' (~ ( '\\\\' | '\"' ) )* '\"' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING
 *
 * Looks to match the characters the constitute the token STRING
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = STRING;


    // /home/ryan/Downloads/Kale.g:115:3: ( '\"' (~ ( '\\\\' | '\"' ) )* '\"' )
    // /home/ryan/Downloads/Kale.g:115:5: '\"' (~ ( '\\\\' | '\"' ) )* '\"'
    {
        MATCHC('"');
        if  (HASEXCEPTION())
        {
            goto ruleSTRINGEx;
        }


        // /home/ryan/Downloads/Kale.g:115:9: (~ ( '\\\\' | '\"' ) )*

        for (;;)
        {
            int alt14=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA14_0 = LA(1);
                if ( (((LA14_0 >= 0x0000) && (LA14_0 <= '!')) || ((LA14_0 >= '#') && (LA14_0 <= '[')) || ((LA14_0 >= ']') && (LA14_0 <= 0xFFFF))))
                {
                    alt14=1;
                }

            }
            switch (alt14)
            {
        	case 1:
        	    // /home/ryan/Downloads/Kale.g:
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '!')) || ((LA(1) >= '#') && (LA(1) <= '[')) || ((LA(1) >= ']') && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleSTRINGEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop14;	/* break out of the loop */
        	    break;
            }
        }
        loop14: ; /* Jump out to here if this rule does not match */


        MATCHC('"');
        if  (HASEXCEPTION())
        {
            goto ruleSTRINGEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSTRINGEx; /* Prevent compiler warnings */
    ruleSTRINGEx: ;

}
// $ANTLR end STRING

//   Comes from: 118:3: ( '\\'' ~ ( '\\'' | '\\\\' ) '\\'' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CHAR
 *
 * Looks to match the characters the constitute the token CHAR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCHAR(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CHAR;


    // /home/ryan/Downloads/Kale.g:118:3: ( '\\'' ~ ( '\\'' | '\\\\' ) '\\'' )
    // /home/ryan/Downloads/Kale.g:118:5: '\\'' ~ ( '\\'' | '\\\\' ) '\\''
    {
        MATCHC('\'');
        if  (HASEXCEPTION())
        {
            goto ruleCHAREx;
        }


        if ( ((LA(1) >= 0x0000) && (LA(1) <= '&')) || ((LA(1) >= '(') && (LA(1) <= '[')) || ((LA(1) >= ']') && (LA(1) <= 0xFFFF)) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleCHAREx;
        }


        MATCHC('\'');
        if  (HASEXCEPTION())
        {
            goto ruleCHAREx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCHAREx; /* Prevent compiler warnings */
    ruleCHAREx: ;

}
// $ANTLR end CHAR

//   Comes from: 120:8: ( ( 'true' | 'false' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BOOLEAN
 *
 * Looks to match the characters the constitute the token BOOLEAN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBOOLEAN(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = BOOLEAN;


    // /home/ryan/Downloads/Kale.g:120:8: ( ( 'true' | 'false' ) )
    // /home/ryan/Downloads/Kale.g:120:10: ( 'true' | 'false' )
    {
        // /home/ryan/Downloads/Kale.g:120:10: ( 'true' | 'false' )
        {
            int alt15=2;
            switch ( LA(1) )
            {
            case 't':
            	{
            		alt15=1;
            	}
                break;
            case 'f':
            	{
            		alt15=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 15;
                EXCEPTION->state        = 0;


                goto ruleBOOLEANEx;

            }

            switch (alt15)
            {
        	case 1:
        	    // /home/ryan/Downloads/Kale.g:120:11: 'true'
        	    {
        	        MATCHS(lit_8);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleBOOLEANEx;
        	        }




        	    }
        	    break;
        	case 2:
        	    // /home/ryan/Downloads/Kale.g:120:18: 'false'
        	    {
        	        MATCHS(lit_9);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleBOOLEANEx;
        	        }




        	    }
        	    break;

            }
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleBOOLEANEx; /* Prevent compiler warnings */
    ruleBOOLEANEx: ;

}
// $ANTLR end BOOLEAN

//   Comes from: 121:11: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start IDENTIFIER
 *
 * Looks to match the characters the constitute the token IDENTIFIER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mIDENTIFIER(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = IDENTIFIER;


    // /home/ryan/Downloads/Kale.g:121:11: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
    // /home/ryan/Downloads/Kale.g:121:13: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
    {
        if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleIDENTIFIEREx;
        }


        // /home/ryan/Downloads/Kale.g:121:37: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*

        for (;;)
        {
            int alt16=2;
            switch ( LA(1) )
            {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
            	{
            		alt16=1;
            	}
                break;

            }

            switch (alt16)
            {
        	case 1:
        	    // /home/ryan/Downloads/Kale.g:
        	    {
        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleIDENTIFIEREx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop16;	/* break out of the loop */
        	    break;
            }
        }
        loop16: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleIDENTIFIEREx; /* Prevent compiler warnings */
    ruleIDENTIFIEREx: ;

}
// $ANTLR end IDENTIFIER

//   Comes from: 122:3: ( ( ' ' | '\\n' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(pKaleLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;


    // /home/ryan/Downloads/Kale.g:122:3: ( ( ' ' | '\\n' )+ )
    // /home/ryan/Downloads/Kale.g:122:5: ( ' ' | '\\n' )+
    {
        // /home/ryan/Downloads/Kale.g:122:5: ( ' ' | '\\n' )+
        {
            int cnt17=0;

            for (;;)
            {
                int alt17=2;
        	switch ( LA(1) )
        	{
        	case '\n':
        	case ' ':
        		{
        			alt17=1;
        		}
        	    break;

        	}

        	switch (alt17)
        	{
        	    case 1:
        	        // /home/ryan/Downloads/Kale.g:
        	        {
        	            if ( LA(1) == '\n' || LA(1) == ' ' )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleWSEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt17 >= 1 )
        		{
        		    goto loop17;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWSEx;
        	}
        	cnt17++;
            }
            loop17: ;	/* Jump to here if this rule does not match */
        }

        {
            LEXSTATE->channel = HIDDEN;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(pKaleLexer ctx)
{
    {
        //  /home/ryan/Downloads/Kale.g:1:8: ( LBRACE | RBRACE | LPAREN | RPAREN | SEMI | COMMA | NL | STATEMENT_DELIMITER | OP_ASSIGN | OP_ADD | OP_SUBTRACT | OP_MULTIPLY | OP_DIVIDE | OP_BOOL_INVERSE | OP_REL_OR | OP_REL_AND | OP_REL_EQ | OP_REL_NEQ | KEYWORD_METHOD | KEYWORD_IF | KEYWORD_ELSE | NUMBER | EXPONENT | STRING | CHAR | BOOLEAN | IDENTIFIER | WS )

        ANTLR3_UINT32 alt18;

        alt18=28;

        alt18 = cdfa18.predict(ctx, RECOGNIZER, ISTREAM, &cdfa18);
        if  (HASEXCEPTION())
        {
            goto ruleTokensEx;
        }

        switch (alt18)
        {
    	case 1:
    	    // /home/ryan/Downloads/Kale.g:1:10: LBRACE
    	    {
    	        /* 1:10: LBRACE */
    	        mLBRACE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // /home/ryan/Downloads/Kale.g:1:17: RBRACE
    	    {
    	        /* 1:17: RBRACE */
    	        mRBRACE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // /home/ryan/Downloads/Kale.g:1:24: LPAREN
    	    {
    	        /* 1:24: LPAREN */
    	        mLPAREN(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // /home/ryan/Downloads/Kale.g:1:31: RPAREN
    	    {
    	        /* 1:31: RPAREN */
    	        mRPAREN(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // /home/ryan/Downloads/Kale.g:1:38: SEMI
    	    {
    	        /* 1:38: SEMI */
    	        mSEMI(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // /home/ryan/Downloads/Kale.g:1:43: COMMA
    	    {
    	        /* 1:43: COMMA */
    	        mCOMMA(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // /home/ryan/Downloads/Kale.g:1:49: NL
    	    {
    	        /* 1:49: NL */
    	        mNL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // /home/ryan/Downloads/Kale.g:1:52: STATEMENT_DELIMITER
    	    {
    	        /* 1:52: STATEMENT_DELIMITER */
    	        mSTATEMENT_DELIMITER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // /home/ryan/Downloads/Kale.g:1:72: OP_ASSIGN
    	    {
    	        /* 1:72: OP_ASSIGN */
    	        mOP_ASSIGN(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // /home/ryan/Downloads/Kale.g:1:82: OP_ADD
    	    {
    	        /* 1:82: OP_ADD */
    	        mOP_ADD(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // /home/ryan/Downloads/Kale.g:1:89: OP_SUBTRACT
    	    {
    	        /* 1:89: OP_SUBTRACT */
    	        mOP_SUBTRACT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // /home/ryan/Downloads/Kale.g:1:101: OP_MULTIPLY
    	    {
    	        /* 1:101: OP_MULTIPLY */
    	        mOP_MULTIPLY(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // /home/ryan/Downloads/Kale.g:1:113: OP_DIVIDE
    	    {
    	        /* 1:113: OP_DIVIDE */
    	        mOP_DIVIDE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // /home/ryan/Downloads/Kale.g:1:123: OP_BOOL_INVERSE
    	    {
    	        /* 1:123: OP_BOOL_INVERSE */
    	        mOP_BOOL_INVERSE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // /home/ryan/Downloads/Kale.g:1:139: OP_REL_OR
    	    {
    	        /* 1:139: OP_REL_OR */
    	        mOP_REL_OR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // /home/ryan/Downloads/Kale.g:1:149: OP_REL_AND
    	    {
    	        /* 1:149: OP_REL_AND */
    	        mOP_REL_AND(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // /home/ryan/Downloads/Kale.g:1:160: OP_REL_EQ
    	    {
    	        /* 1:160: OP_REL_EQ */
    	        mOP_REL_EQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // /home/ryan/Downloads/Kale.g:1:170: OP_REL_NEQ
    	    {
    	        /* 1:170: OP_REL_NEQ */
    	        mOP_REL_NEQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // /home/ryan/Downloads/Kale.g:1:181: KEYWORD_METHOD
    	    {
    	        /* 1:181: KEYWORD_METHOD */
    	        mKEYWORD_METHOD(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 20:
    	    // /home/ryan/Downloads/Kale.g:1:196: KEYWORD_IF
    	    {
    	        /* 1:196: KEYWORD_IF */
    	        mKEYWORD_IF(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 21:
    	    // /home/ryan/Downloads/Kale.g:1:207: KEYWORD_ELSE
    	    {
    	        /* 1:207: KEYWORD_ELSE */
    	        mKEYWORD_ELSE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 22:
    	    // /home/ryan/Downloads/Kale.g:1:220: NUMBER
    	    {
    	        /* 1:220: NUMBER */
    	        mNUMBER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 23:
    	    // /home/ryan/Downloads/Kale.g:1:227: EXPONENT
    	    {
    	        /* 1:227: EXPONENT */
    	        mEXPONENT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 24:
    	    // /home/ryan/Downloads/Kale.g:1:236: STRING
    	    {
    	        /* 1:236: STRING */
    	        mSTRING(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 25:
    	    // /home/ryan/Downloads/Kale.g:1:243: CHAR
    	    {
    	        /* 1:243: CHAR */
    	        mCHAR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 26:
    	    // /home/ryan/Downloads/Kale.g:1:248: BOOLEAN
    	    {
    	        /* 1:248: BOOLEAN */
    	        mBOOLEAN(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 27:
    	    // /home/ryan/Downloads/Kale.g:1:256: IDENTIFIER
    	    {
    	        /* 1:256: IDENTIFIER */
    	        mIDENTIFIER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 28:
    	    // /home/ryan/Downloads/Kale.g:1:267: WS
    	    {
    	        /* 1:267: WS */
    	        mWS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
