/** \file
 *  This C header file was generated by $ANTLR version 3.5.1
 *
 *     -  From the grammar source file : /home/ryan/Downloads/Kale.g
 *     -                            On : 2022-07-19 20:49:54
 *     -                for the parser : KaleParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser 
KaleParser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pKaleParser, which is returned from a call to KaleParserNew().
 *
 * The methods in pKaleParser are  as follows:
 *
 *  - 
 KaleParser_parse_return
      pKaleParser->parse(pKaleParser)
 *  - 
 KaleParser_method_declaration_return
      pKaleParser->method_declaration(pKaleParser)
 *  - 
 KaleParser_identifier_list_return
      pKaleParser->identifier_list(pKaleParser)
 *  - 
 KaleParser_block_return
      pKaleParser->block(pKaleParser)
 *  - 
 KaleParser_statements_return
      pKaleParser->statements(pKaleParser)
 *  - 
 KaleParser_statement_return
      pKaleParser->statement(pKaleParser)
 *  - 
 KaleParser_assignment_return
      pKaleParser->assignment(pKaleParser)
 *  - 
 KaleParser_function_call_return
      pKaleParser->function_call(pKaleParser)
 *  - 
 KaleParser_expression_return
      pKaleParser->expression(pKaleParser)
 *  - 
 KaleParser_or_expression_return
      pKaleParser->or_expression(pKaleParser)
 *  - 
 KaleParser_and_expression_return
      pKaleParser->and_expression(pKaleParser)
 *  - 
 KaleParser_equ_expression_return
      pKaleParser->equ_expression(pKaleParser)
 *  - 
 KaleParser_add_expression_return
      pKaleParser->add_expression(pKaleParser)
 *  - 
 KaleParser_mul_expression_return
      pKaleParser->mul_expression(pKaleParser)
 *  - 
 KaleParser_unary_expression_return
      pKaleParser->unary_expression(pKaleParser)
 *  - 
 KaleParser_atom_return
      pKaleParser->atom(pKaleParser)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_KaleParser_H
#define _KaleParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct KaleParser_Ctx_struct KaleParser, * pKaleParser;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif
typedef struct KaleParser_parse_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    KaleParser_parse_return;



typedef struct KaleParser_method_declaration_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    KaleParser_method_declaration_return;



typedef struct KaleParser_identifier_list_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    KaleParser_identifier_list_return;



typedef struct KaleParser_block_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    KaleParser_block_return;



typedef struct KaleParser_statements_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    KaleParser_statements_return;



typedef struct KaleParser_statement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    KaleParser_statement_return;



typedef struct KaleParser_assignment_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    KaleParser_assignment_return;



typedef struct KaleParser_function_call_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    KaleParser_function_call_return;



typedef struct KaleParser_expression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    KaleParser_expression_return;



typedef struct KaleParser_or_expression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    KaleParser_or_expression_return;



typedef struct KaleParser_and_expression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    KaleParser_and_expression_return;



typedef struct KaleParser_equ_expression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    KaleParser_equ_expression_return;



typedef struct KaleParser_add_expression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    KaleParser_add_expression_return;



typedef struct KaleParser_mul_expression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    KaleParser_mul_expression_return;



typedef struct KaleParser_unary_expression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    KaleParser_unary_expression_return;



typedef struct KaleParser_atom_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    KaleParser_atom_return;




/** Context tracking structure for 
KaleParser

 */
struct KaleParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;

     KaleParser_parse_return
     (*parse)	(struct KaleParser_Ctx_struct * ctx);

     KaleParser_method_declaration_return
     (*method_declaration)	(struct KaleParser_Ctx_struct * ctx);

     KaleParser_identifier_list_return
     (*identifier_list)	(struct KaleParser_Ctx_struct * ctx);

     KaleParser_block_return
     (*block)	(struct KaleParser_Ctx_struct * ctx);

     KaleParser_statements_return
     (*statements)	(struct KaleParser_Ctx_struct * ctx);

     KaleParser_statement_return
     (*statement)	(struct KaleParser_Ctx_struct * ctx);

     KaleParser_assignment_return
     (*assignment)	(struct KaleParser_Ctx_struct * ctx);

     KaleParser_function_call_return
     (*function_call)	(struct KaleParser_Ctx_struct * ctx);

     KaleParser_expression_return
     (*expression)	(struct KaleParser_Ctx_struct * ctx);

     KaleParser_or_expression_return
     (*or_expression)	(struct KaleParser_Ctx_struct * ctx);

     KaleParser_and_expression_return
     (*and_expression)	(struct KaleParser_Ctx_struct * ctx);

     KaleParser_equ_expression_return
     (*equ_expression)	(struct KaleParser_Ctx_struct * ctx);

     KaleParser_add_expression_return
     (*add_expression)	(struct KaleParser_Ctx_struct * ctx);

     KaleParser_mul_expression_return
     (*mul_expression)	(struct KaleParser_Ctx_struct * ctx);

     KaleParser_unary_expression_return
     (*unary_expression)	(struct KaleParser_Ctx_struct * ctx);

     KaleParser_atom_return
     (*atom)	(struct KaleParser_Ctx_struct * ctx);
    // Delegated rules

    const char * (*getGrammarFileName)();
    void            (*reset)  (struct KaleParser_Ctx_struct * ctx);
    void	    (*free)   (struct KaleParser_Ctx_struct * ctx);
/* @headerFile.members() */
pANTLR3_BASE_TREE_ADAPTOR	adaptor;
pANTLR3_VECTOR_FACTORY		vectors;
/* End @headerFile.members() */
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pKaleParser KaleParserNew         (
pANTLR3_COMMON_TOKEN_STREAM
 instream);
ANTLR3_API pKaleParser KaleParserNewSSD      (
pANTLR3_COMMON_TOKEN_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
parser
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define BOOLEAN      4
#define CHAR      5
#define COMMA      6
#define EXPONENT      7
#define IDENTIFIER      8
#define KEYWORD_ELSE      9
#define KEYWORD_IF      10
#define KEYWORD_METHOD      11
#define LBRACE      12
#define LPAREN      13
#define NL      14
#define NUMBER      15
#define OP_ADD      16
#define OP_ASSIGN      17
#define OP_BOOL_INVERSE      18
#define OP_DIVIDE      19
#define OP_MULTIPLY      20
#define OP_REL_AND      21
#define OP_REL_EQ      22
#define OP_REL_NEQ      23
#define OP_REL_OR      24
#define OP_SUBTRACT      25
#define RBRACE      26
#define RPAREN      27
#define SEMI      28
#define STATEMENT_DELIMITER      29
#define STRING      30
#define WS      31
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for KaleParser
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
