/** \file
 *  This C header file was generated by $ANTLR version 3.5.1
 *
 *     -  From the grammar source file : /home/ryan/Downloads/Kale.g
 *     -                            On : 2022-07-19 20:49:54
 *     -                 for the lexer : KaleLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
KaleLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pKaleLexer, which is returned from a call to KaleLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pKaleLexer are  as follows:
 *
 *  - 
 void
      pKaleLexer->LBRACE(pKaleLexer)
 *  - 
 void
      pKaleLexer->RBRACE(pKaleLexer)
 *  - 
 void
      pKaleLexer->LPAREN(pKaleLexer)
 *  - 
 void
      pKaleLexer->RPAREN(pKaleLexer)
 *  - 
 void
      pKaleLexer->SEMI(pKaleLexer)
 *  - 
 void
      pKaleLexer->COMMA(pKaleLexer)
 *  - 
 void
      pKaleLexer->NL(pKaleLexer)
 *  - 
 void
      pKaleLexer->STATEMENT_DELIMITER(pKaleLexer)
 *  - 
 void
      pKaleLexer->OP_ASSIGN(pKaleLexer)
 *  - 
 void
      pKaleLexer->OP_ADD(pKaleLexer)
 *  - 
 void
      pKaleLexer->OP_SUBTRACT(pKaleLexer)
 *  - 
 void
      pKaleLexer->OP_MULTIPLY(pKaleLexer)
 *  - 
 void
      pKaleLexer->OP_DIVIDE(pKaleLexer)
 *  - 
 void
      pKaleLexer->OP_BOOL_INVERSE(pKaleLexer)
 *  - 
 void
      pKaleLexer->OP_REL_OR(pKaleLexer)
 *  - 
 void
      pKaleLexer->OP_REL_AND(pKaleLexer)
 *  - 
 void
      pKaleLexer->OP_REL_EQ(pKaleLexer)
 *  - 
 void
      pKaleLexer->OP_REL_NEQ(pKaleLexer)
 *  - 
 void
      pKaleLexer->KEYWORD_METHOD(pKaleLexer)
 *  - 
 void
      pKaleLexer->KEYWORD_IF(pKaleLexer)
 *  - 
 void
      pKaleLexer->KEYWORD_ELSE(pKaleLexer)
 *  - 
 void
      pKaleLexer->NUMBER(pKaleLexer)
 *  - 
 void
      pKaleLexer->EXPONENT(pKaleLexer)
 *  - 
 void
      pKaleLexer->STRING(pKaleLexer)
 *  - 
 void
      pKaleLexer->CHAR(pKaleLexer)
 *  - 
 void
      pKaleLexer->BOOLEAN(pKaleLexer)
 *  - 
 void
      pKaleLexer->IDENTIFIER(pKaleLexer)
 *  - 
 void
      pKaleLexer->WS(pKaleLexer)
 *  - 
 void
      pKaleLexer->Tokens(pKaleLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_KaleLexer_H
#define _KaleLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct KaleLexer_Ctx_struct KaleLexer, * pKaleLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
KaleLexer

 */
struct KaleLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mLBRACE)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mRBRACE)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mLPAREN)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mRPAREN)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mSEMI)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mCOMMA)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mNL)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mSTATEMENT_DELIMITER)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mOP_ASSIGN)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mOP_ADD)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mOP_SUBTRACT)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mOP_MULTIPLY)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mOP_DIVIDE)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mOP_BOOL_INVERSE)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mOP_REL_OR)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mOP_REL_AND)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mOP_REL_EQ)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mOP_REL_NEQ)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mKEYWORD_METHOD)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mKEYWORD_IF)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mKEYWORD_ELSE)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mNUMBER)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mEXPONENT)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mSTRING)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mCHAR)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mBOOLEAN)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mIDENTIFIER)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct KaleLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct KaleLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct KaleLexer_Ctx_struct * ctx);
    void	    (*free)   (struct KaleLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pKaleLexer KaleLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pKaleLexer KaleLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define BOOLEAN      4
#define CHAR      5
#define COMMA      6
#define EXPONENT      7
#define IDENTIFIER      8
#define KEYWORD_ELSE      9
#define KEYWORD_IF      10
#define KEYWORD_METHOD      11
#define LBRACE      12
#define LPAREN      13
#define NL      14
#define NUMBER      15
#define OP_ADD      16
#define OP_ASSIGN      17
#define OP_BOOL_INVERSE      18
#define OP_DIVIDE      19
#define OP_MULTIPLY      20
#define OP_REL_AND      21
#define OP_REL_EQ      22
#define OP_REL_NEQ      23
#define OP_REL_OR      24
#define OP_SUBTRACT      25
#define RBRACE      26
#define RPAREN      27
#define SEMI      28
#define STATEMENT_DELIMITER      29
#define STRING      30
#define WS      31
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for KaleLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
